# Generated by Django 4.2.7 on 2023-11-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelis', '0002_estreno_proxima_alter_peli_created_alter_peli_imagen_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estreno',
        ),
        migrations.DeleteModel(
            name='Proxima',
        ),
        migrations.AddField(
            model_name='peli',
            name='tipo',
            field=models.CharField(default='PROXIMAMENTE', max_length=100, verbose_name='Tipo'),
        ),
    ]
